### ISSUE TITLE
await agent.ready not working (hanging)

### ISSUE THREAD

**Issue by vegedreamgagnoa** [corellium/corellium-api#12]
Calling await agent.ready() never returns and hanging up the entire script/program. Previously there're no problems. 

Please fix this.

**Comment by vegedreamgagnoa** [comment]
Update: **it's not working on MacOS, Windows, and Linux.** Seems like there's some problems with agent connection on corellium side.

Please advise and fix.

**Comment by vegedreamgagnoa** [comment]
Please advise and fix

**Comment by vegedreamgagnoa** [comment]
@matthewh @sbingner 

Using a sample script in examples folder to install android APK.

Logging in...
Getting projects list...
Getting instances...
Getting agent...
Waiting until agent is ready...


for hours with no sign of ending.

**Comment by cmwdotme** [comment]
We are aware of the issue and are actively working on a fix. Hold tight.

**Comment by sbingner** [comment]
This has been resolved; do let us know if you run into any more issues like this, thank you.
