### ISSUE TITLE
Agent stuck on an endless Promise

### ISSUE THREAD

**Issue by realgam3** [corellium/corellium-api#21]
After a possible change in the backend or one of the libraries like WebSocket,
The agent is stuck on endless loop trying to connect WebSocket address with https instead of wss,
When this is fixed then the code doesn't get the right id from the message because it thinks it's a binary message instead of string message.

The code with the issues:
https://github.com/corellium/corellium-api/blob/master/src/agent.js#L138
```javascript
    async _connect() {
        this.pending = new Map();

        const endpoint = await this.instance.agentEndpoint();
        if (!endpoint) {
            this.pendingConnect = false;
            throw new Error("Instance likely does not exist");
        }

        // Detect if a disconnection happened before we were able to get the agent endpoint.
        if (!this.pendingConnect) throw new Error("connection cancelled");

        let ws = new WebSocket(endpoint);

        this.ws = ws;

        ws.on("message", (data) => {
            try {
                let message;
                let id;
                if (typeof data === "string") {
                    message = JSON.parse(data);
                    id = message["id"];
                } else if (data.length >= 8) {
                    id = data.readUInt32LE(0);
                    message = data.slice(8);
                }

                let handler = this.pending.get(id);
                if (handler) {
                    // will work regardless of whether handler returns a promise
                    Promise.resolve(handler(null, message)).then((shouldDelete) => {
                        if (shouldDelete) this.pending.delete(id);
                    });
                }
            } catch (err) {
                console.error("error in agent message handler", err);
            }
        });
```

To reproduce:
1) Create an instance
2) call `instance.waitForAgentReady()` or `agent.ready()`

**Comment by dthagard** [comment]
Fixed in https://github.com/corellium/corellium-api/commit/452828a75d6f329c7a35ea81a7e9f0a0922f1bfb

**Comment by realgam3** [comment]
> Fixed in https://github.com/corellium/corellium-api/commit/452828a75d6f329c7a35ea81a7e9f0a0922f1bfb

I do think the way I wrote it in the PR was better and handled more  complicated scenarios from the WebSocket but it good to know it's fixed
